/* ============================================================
   Kernveil — Seeded demo data
   All records are fictional sample data for the interactive
   product preview. They are not real scans or customer data.
   ============================================================ */

export const WORKSPACE = {
  name: "Acme Retail (sample)",
  plan: "Demo workspace",
};

export const OVERVIEW = {
  risk: 74,
  critical: 2,
  high: 9,
  medium: 8,
  low: 8,
  assets: 14,
  open: 17,
  inProgress: 3,
  resolved: 23,
  total: 30,
  remedPct: 23,
  delta: -6,
  lastSync: "2 minutes ago",
};

export const RISK_SERIES = [
  { label: "Jun", value: 46 },
  { label: "Jul", value: 42 },
  { label: "Aug", value: 38 },
  { label: "Sep", value: 44 },
  { label: "Oct", value: 41 },
  { label: "Nov", value: 35 },
  { label: "Dec", value: 31 },
  { label: "Jan", value: 26 },
  { label: "Feb", value: 30 },
  { label: "Mar", value: 27 },
  { label: "Apr", value: 24 },
  { label: "May", value: 22 },
];

export const ASSETS = [
  { id: "prod-web-01", name: "prod-web-01", type: "server", env: "Production", source: "Cloud", risk: "high", last: "2m ago", host: "18.208.11.4" },
  { id: "acme-retail-primary", name: "acme-retail-primary", type: "storage", env: "Production", source: "Cloud", risk: "critical", last: "2m ago", host: "acme-retail-primary.s3.aws" },
  { id: "db-main", name: "db-main", type: "database", env: "Production", source: "Cloud", risk: "high", last: "2m ago", host: "10.0.6.22:5432" },
  { id: "billing-app", name: "billing-app", type: "application", env: "Production", source: "Code", risk: "medium", last: "6m ago", host: "billing.acme.dev" },
  { id: "shop-api", name: "shop-api", type: "api", env: "Production", source: "Code", risk: "medium", last: "6m ago", host: "api.acme.dev" },
  { id: "acme.com", name: "acme.com", type: "website", env: "Production", source: "Website", risk: "high", last: "8m ago", host: "ssl acme.com" },
  { id: "identity-provider", name: "identity-provider", type: "identity", env: "Production", source: "Cloud", risk: "low", last: "21m ago", host: "id.acme.dev" },
  { id: "backup-system", name: "backup-system", type: "storage", env: "Production", source: "Backups", risk: "healthy", last: "1h ago", host: "backups.acme.internal" },
  { id: "staging-web-02", name: "staging-web-02", type: "server", env: "Staging", source: "Cloud", risk: "low", last: "3h ago", host: "10.0.20.9" },
  { id: "checkout-svc", name: "checkout-svc", type: "application", env: "Production", source: "Code", risk: "healthy", last: "6m ago", host: "checkout.acme.dev" },
  { id: "orders-bucket", name: "orders-bucket", type: "storage", env: "Staging", source: "Cloud", risk: "medium", last: "14m ago", host: "orders-bucket.s3.aws" },
  { id: "cms-admin", name: "cms-admin", type: "application", env: "Production", source: "Code", risk: "high", last: "9m ago", host: "admin.acme.dev" },
  { id: "legacy-api-v2", name: "legacy-api-v2", type: "api", env: "Production", source: "Code", risk: "medium", last: "1h ago", host: "api-v2.acme.dev" },
  { id: "mail-relay", name: "mail-relay", type: "server", env: "Production", source: "Cloud", risk: "low", last: "2h ago", host: "10.0.8.30" },
];

export const FINDINGS = [
  {
    id: "publicly-exposed-storage",
    title: "Publicly exposed storage resource",
    severity: "critical",
    category: "Exposure",
    asset: "acme-retail-primary",
    status: "open",
    first: "Aug 28, 2026",
    last: "2 minutes ago",
    summary: "A storage resource that holds customer backup data is publicly readable from the internet.",
    detected: "The storage resource <code>acme-retail-primary</code> allows public read access. Its access-control list grants <code class='bad'>AllUsers</code> read permission, and the resource is resolvable from a public endpoint.",
    why: "This resource contains compressed backups of customer order history. Because it is publicly readable, anyone on the internet — not just your team — could download that data. There is no evidence the data has been accessed by anyone else, but the exposure exists right now and is trivial to exploit.",
    impact: "Sensitive data at rest",
    evidence: [
      { key: "Resource", value: "acme-retail-primary" },
      { key: "Region", value: "us-east-1" },
      { key: "Public URL", value: "https://acme-retail-primary.s3.aws" },
      { key: "ACL", value: "AllUsers:READ" },
      { key: "Detection method", value: "configuration audit" },
    ],
    steps: [
      "Sign in to your cloud console, open <code>acme-retail-primary</code>, and open the Permissions tab.",
      "Remove the public <code>AllUsers</code> grant. Add the service role used by <code>prod-web-01</code> instead.",
      "Run a verification: Kernveil will re-check this resource within minutes and mark the finding resolved.",
    ],
    related: ["prod-web-01", "backup-system"],
    history: [
      { time: "Aug 28 · 09:14", text: "First detected", c: "var(--red)" },
      { time: "Aug 31 · 14:40", text: "Re-checked — still exposed", c: "var(--red)" },
      { time: "Sep 02 · 10:05", text: "Assigned to engineering lead", c: "var(--amber)" },
      { time: "Last check · 2m ago", text: "Still open — next step recommended", c: "var(--slate)" },
    ],
  },
  {
    id: "open-db-port",
    title: "Open database port on shared host",
    severity: "high",
    category: "Configuration",
    asset: "db-main",
    status: "open",
    first: "Aug 30, 2026",
    last: "2 minutes ago",
    summary: "PostgreSQL is listening on a port reachable from the public internet.",
    detected: "The database server <code>db-main</code> accepts connections on port <code class='bad'>5432</code> from 0.0.0.0/0. The service is not restricted to your internal network.",
    why: "A database that accepts connections from the whole internet is exposed to password-guessing and any flaw in the client library. Your data layer should only accept traffic from your application servers.",
    impact: "Data exposure",
    evidence: [
      { key: "Host", value: "10.0.6.22:5432" },
      { key: "Rule", value: "0.0.0.0/0 · TCP:5432" },
      { key: "Engine", value: "PostgreSQL 15" },
    ],
    steps: [
      "Open your cloud firewall rules for the host running <code>db-main</code>.",
      "Remove the <code>0.0.0.0/0</code> rule. Add a rule allowing only your application subnet.",
      "Confirm the app still connects, then re-check here.",
    ],
    related: ["prod-web-01", "billing-app"],
    history: [
      { time: "Aug 30 · 11:22", text: "First detected", c: "var(--orange)" },
      { time: "Last check · 2m ago", text: "Still open", c: "var(--slate)" },
    ],
  },
  {
    id: "vulnerable-dependency",
    title: "Vulnerable dependency in a repository",
    severity: "high",
    category: "Dependencies",
    asset: "billing-app",
    status: "in-progress",
    first: "Sep 05, 2026",
    last: "6m ago",
    summary: "The billing service depends on a library with a known, exploitable vulnerability.",
    detected: "The repository for <code>billing-app</code> pins a version of <code>xml2js</code> affected by a documented denial-of-service and integrity issue. The fix is a single minor-version bump.",
    why: "Malicious input could trip the flawed parser and take the billing API offline. A dependency bump is low-risk and closes the issue.",
    impact: "Service availability",
    evidence: [
      { key: "Repository", value: "acme/billing-app" },
      { key: "Dependency", value: "xml2js@0.4.19" },
      { key: "Fixed in", value: "≥ 0.5.0" },
      { key: "Manifest", value: "package-lock.json" },
    ],
    steps: [
      "In <code>billing-app</code>, run <code>npm audit fix</code> or bump <code>xml2js</code> to ≥ 0.5.0.",
      "Run the test suite and deploy as usual.",
    ],
    related: ["billing-app"],
    history: [
      { time: "Sep 05 · 16:02", text: "First detected", c: "var(--orange)" },
      { time: "Sep 06 · 09:31", text: "Fix branch opened", c: "var(--amber)" },
    ],
  },
  {
    id: "permissive-access-policy",
    title: "Overly permissive access policy",
    severity: "medium",
    category: "Identity",
    asset: "billing-app",
    status: "open",
    first: "Sep 01, 2026",
    last: "6m ago",
    summary: "A service account can read and write more than the app actually needs.",
    detected: "The service account used by <code>billing-app</code> has wildcard write access to object storage, wider than any valid use case.",
    why: "If this credential is ever leaked, the blast radius is the whole storage estate instead of one prefix. Narrowing the policy limits what a compromise could touch.",
    impact: "Wider compromise blast radius",
    evidence: [
      { key: "Principal", value: "arn:svc:billing-app" },
      { key: "Statement", value: "s3:PutObject on arn:…:bucket/*" },
    ],
    steps: [
      "Restrict the policy to the two prefixes billing actually uses.",
      "Split read and write roles so a leak cannot overwrite data.",
    ],
    related: ["billing-app"],
    history: [
      { time: "Sep 01 · 13:47", text: "First detected", c: "var(--amber)" },
    ],
  },
  {
    id: "expiring-certificate",
    title: "TLS certificate expiring soon",
    severity: "high",
    category: "Configuration",
    asset: "acme.com",
    status: "open",
    first: "Sep 10, 2026",
    last: "8m ago",
    summary: "The certificate for your public site expires in 11 days. Renewal has not started.",
    detected: "The TLS certificate presented by <code>acme.com</code> expires on <b>Sep 25, 2026</b>. No renewal validates in 9 days.",
    why: "When it expires, browsers will block the site and customer checkout breaks. Because this is on the critical path, it should move before backlog security items.",
    impact: "Customer-facing outage",
    evidence: [
      { key: "Host", value: "acme.com" },
      { key: "Expires", value: "Sep 25, 2026" },
      { key: "Issuer", value: "Let's Encrypt" },
    ],
    steps: [
      "Confirm your certificate auto-renewal job is still enabled.",
      "If manual, renew now via your DNS provider.",
    ],
    related: ["acme.com"],
    history: [
      { time: "Sep 10 · 07:00", text: "First detected", c: "var(--orange)" },
    ],
  },
  {
    id: "missing-security-headers",
    title: "Missing security configuration on public site",
    severity: "medium",
    category: "Configuration",
    asset: "acme.com",
    status: "open",
    first: "Sep 02, 2026",
    last: "8m ago",
    summary: "The marketing site is missing recommended content-security and framing headers.",
    detected: "Responses from <code>acme.com</code> do not send <code class='bad'>Content-Security-Policy</code> or <code class='bad'>X-Frame-Options</code> headers.",
    why: "These headers are low-cost hardening. Missing them increases the risk of injected content and clickjacking attacks on the public site.",
    impact: "Client-side attack surface",
    evidence: [
      { key: "Host", value: "acme.com" },
      { key: "Missing", value: "CSP · X-Frame-Options" },
    ],
    steps: [
      "Add a starter CSP header (e.g. <code>default-src 'self'</code>).",
      "Add <code>X-Frame-Options: DENY</code> and re-check.",
    ],
    related: ["acme.com"],
    history: [
      { time: "Sep 02 · 12:18", text: "First detected", c: "var(--amber)" },
    ],
  },
  {
    id: "repo-permissions",
    title: "Public write access on a repository",
    severity: "high",
    category: "Repositories",
    asset: "cms-admin",
    status: "in-progress",
    first: "Aug 26, 2026",
    last: "9m ago",
    summary: "A repository can be written to by anyone on the internet.",
    detected: "The repository <code>acme/cms-admin</code> allows public users to open pull requests and merge on approval, and archive protections are off.",
    why: "An attacker who enters via an accepted PR could ship malicious code to the CMS admin. Tightening permissions and requiring review removes that route.",
    impact: "Supply-chain risk",
    evidence: [
      { key: "Repository", value: "acme/cms-admin" },
      { key: "Public write", value: "enabled" },
      { key: "Merge guard", value: "off" },
    ],
    steps: [
      "Set the repository to private or restrict write access to maintainers.",
      "Require a pull-request review and disable force-push.",
    ],
    related: ["cms-admin"],
    history: [
      { time: "Aug 26 · 08:50", text: "First detected", c: "var(--orange)" },
      { time: "Sep 06 · 15:20", text: "Repo set to private", c: "var(--green)" },
      { time: "Last check · 9m ago", text: "Merge guard still off", c: "var(--amber)" },
    ],
  },
  {
    id: "weak-backup-policy",
    title: "Incomplete backup retention policy",
    severity: "low",
    category: "Backups",
    asset: "backup-system",
    status: "open",
    first: "Aug 22, 2026",
    last: "1h ago",
    summary: "Monthly backups are retained for only 60 days.",
    detected: "The backup schedule retains daily snapshots for 7 days but monthly backups are pruned after 60 days.",
    why: "If a problem goes unnoticed for a quarter, there is no clean monthly restore point. This is a low-urgency operational risk, not an active exposure.",
    impact: "Recovery gap",
    evidence: [
      { key: "Schedule", value: "monthly" },
      { key: "Retention", value: "60 days" },
    ],
    steps: [
      "Extend monthly retention to 13 months when convenient.",
    ],
    related: ["backup-system"],
    history: [
      { time: "Aug 22 · 19:30", text: "First detected", c: "var(--slate)" },
    ],
  },
  {
    id: "exposed-debug-endpoint",
    title: "Debug endpoint enabled in production",
    severity: "medium",
    category: "Exposure",
    asset: "shop-api",
    status: "resolved",
    first: "Jul 19, 2026",
    last: "6m ago",
    summary: "A verbose error route was answering real traffic. It has been disabled.",
    detected: "The endpoint <code>/__debug</code> returned stack traces and environment names in production.",
    why: "Detailed errors help attackers map your internals. The team disabled the route in a hotfix.",
    impact: "Information disclosure",
    evidence: [
      { key: "Endpoint", value: "/__debug" },
      { key: "Status", value: "disabled" },
    ],
    steps: [],
    related: ["shop-api"],
    history: [
      { time: "Jul 19 · 22:41", text: "First detected", c: "var(--amber)" },
      { time: "Jul 22 · 11:15", text: "Hotfix deployed — resolved", c: "var(--green)" },
    ],
  },
  {
    id: "service-account-rotation",
    title: "Long-lived service credential needs rotation",
    severity: "high",
    category: "Identity",
    asset: "identity-provider",
    status: "open",
    first: "Sep 06, 2026",
    last: "21m ago",
    summary: "A machine credential used in scripts has not been rotated in 11 months.",
    detected: "The credential <code>deploy-bot</code> has been valid for 347 days and is referenced in public build logs.",
    why: "Long-lived credentials that show up in logs are prime targets. Rotation cuts the usefulness of anything already leaked.",
    impact: "Credential exposure",
    evidence: [
      { key: "Credential", value: "deploy-bot" },
      { key: "Age", value: "347 days" },
      { key: "Seen in", value: "public CI logs" },
    ],
    steps: [
      "Rotate the deploy-bot credential.",
      "Switch the build pipeline to short-lived tokens.",
    ],
    related: ["identity-provider", "billing-app"],
    history: [
      { time: "Sep 06 · 10:12", text: "First detected", c: "var(--orange)" },
    ],
  },
  {
    id: "jwt-library-cve",
    title: "Known vulnerability in authentication library",
    severity: "high",
    category: "Dependencies",
    asset: "shop-api",
    status: "open",
    first: "Sep 03, 2026",
    last: "6m ago",
    summary: "The API's JWT library has a documented signature-confusion flaw.",
    detected: "<code>jsonwebtoken@8.5.1</code> is affected by an advisory describing algorithm-confusion tokens.",
    why: "Algorithm confusion can let an attacker forge valid tokens if the public key is guessable. Most apps are not realistically targeted, but the fix is a one-line bump.",
    impact: "Auth bypass risk",
    evidence: [
      { key: "Library", value: "jsonwebtoken@8.5.1" },
      { key: "Advisory", value: "GHSA-array-jwt" },
    ],
    steps: [
      "Bump <code>jsonwebtoken</code> to ≥ 9.0.0.",
    ],
    related: ["shop-api"],
    history: [
      { time: "Sep 03 · 17:44", text: "First detected", c: "var(--orange)" },
    ],
  },
  {
    id: "unencrypted-uploads",
    title: "Uploads stored without encryption at rest",
    severity: "medium",
    category: "Configuration",
    asset: "orders-bucket",
    status: "in-progress",
    first: "Aug 18, 2026",
    last: "14m ago",
    summary: "A staging bucket stores order exports without server-side encryption.",
    detected: "The staging resource <code>orders-bucket</code> has default encryption disabled.",
    why: "Encryption at rest is a cheap, automatic safeguard. Staging data is less sensitive, but defaulting to encrypted is the safer habit.",
    impact: "Sensitive data at rest",
    evidence: [
      { key: "Resource", value: "orders-bucket" },
      { key: "Encryption", value: "disabled" },
    ],
    steps: [
      "Enable default encryption on the bucket in staging, then in production.",
    ],
    related: ["orders-bucket"],
    history: [
      { time: "Aug 18 · 09:05", text: "First detected", c: "var(--amber)" },
      { time: "Sep 04 · 14:10", text: "Staging enabled — prod pending", c: "var(--amber)" },
    ],
  },
  {
    id: "staging-cors-open",
    title: "Permissive CORS on staging endpoint",
    severity: "low",
    category: "Configuration",
    asset: "staging-web-02",
    status: "approved",
    first: "Aug 12, 2026",
    last: "3h ago",
    summary: "A staging API allows any origin. Approved to revert after launch.",
    detected: "The staging server responds <code>Access-Control-Allow-Origin: *</code>.",
    why: "Any website could read staging responses. It is staging-only, so the team approved fixing it during the current sprint.",
    impact: "Cross-origin data read",
    evidence: [
      { key: "Host", value: "staging-web-02" },
      { key: "ACAO", value: "*" },
    ],
    steps: [
      "Restrict CORS to the staging app origin.",
    ],
    related: ["staging-web-02"],
    history: [
      { time: "Aug 12 · 08:00", text: "First detected", c: "var(--slate)" },
      { time: "Sep 07 · 16:25", text: "Fix scheduled — awaiting approval", c: "var(--cyan)" },
    ],
  },
  {
    id: "admin-login-limit",
    title: "No rate limiting on admin login",
    severity: "medium",
    category: "Configuration",
    asset: "cms-admin",
    status: "open",
    first: "Aug 29, 2026",
    last: "9m ago",
    summary: "The admin login endpoint has no protection against repeated guesses.",
    detected: "Requests to the CMS login endpoint are not rate-limited or throttled, and there is no lockout.",
    why: "Brute-force attempts are cheap. Rate limiting and lockout make guessing infeasible at internet scale and give you a log signal if someone tries.",
    impact: "Credential guessing",
    evidence: [
      { key: "Endpoint", value: "/admin/login" },
      { key: "Throttle", value: "none" },
    ],
    steps: [
      "Add per-IP rate limiting plus a short lockout after failures.",
      "Deploy with the same config in staging first.",
    ],
    related: ["cms-admin"],
    history: [
      { time: "Aug 29 · 10:08", text: "First detected", c: "var(--amber)" },
    ],
  },
];

export const CONNECTORS = [
  {
    id: "github",
    name: "GitHub",
    desc: "Repository health, dependency manifests, and code exposure for the repositories your team works in.",
    state: "available",
    type: "Code",
  },
  {
    id: "cloud",
    name: "Cloud environment",
    desc: "Storage, networking, compute, and identity posture for your primary cloud account.",
    state: "available",
    type: "Cloud",
  },
  {
    id: "website",
    name: "Website",
    desc: "Public exposure checks, TLS health, and security headers for the sites you answer for.",
    state: "available",
    type: "Website",
  },
  {
    id: "identity",
    name: "Identity provider",
    desc: "Credential age, unusual sign-in patterns, and role hygiene across the exported identity directory you review. No live provider is ever contacted.",
    state: "available",
    type: "Identity",
  },
  {
    id: "backup",
    name: "Backup system",
    desc: "Retention health, restore coverage, and whether your backups would actually restore.",
    state: "available",
    type: "Backups",
  },
  {
    id: "saas",
    name: "SaaS apps",
    desc: "Connected third-party tools, their data access, and who can reach them.",
    state: "coming",
    type: "SaaS",
  },
];

export const ASSET_FINDING_MAP = FINDINGS.reduce((m, f) => {
  (m[f.asset] = m[f.asset] || []).push(f);
  return m;
}, {});